Add statesync example script
confio/tgrade pull request #417
Opened 2022-07-04 15:11 UTC by pinosu

Resolves #415

2022-07-06 06:45 UTC, alpe requested changes
Good start! I would strip it down to state sync only.

2022-07-06 06:45 UTC, alpe commented on scripts/statesync.sh
> +export TGRADE_P2P_MAX_NUM_OUTBOUND_PEERS=200
This is a node config that is not needed here

2022-07-06 06:45 UTC, alpe commented on scripts/statesync.sh
> +export TGRADE_STATESYNC_RPC_SERVERS="$SNAP_RPC,$SNAP_RPC"
Please use "$SNAP_RPC,https://tgrade-mainnet-rpc.allthatnode.com:26657" so that we have 2 independent sources

2022-07-06 10:21 UTC, pinosu commented on scripts/statesync.sh
> +export TGRADE_STATESYNC_TRUST_HASH=$TRUST_HASH
I tested it multiple times and it works fine on my machine.

2022-07-07 07:53 UTC, maurolacy approved these changes
LGTM.

2022-07-07 07:53 UTC, maurolacy commented on scripts/statesync.sh
> +LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height);
```suggestion
LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height)
```

2022-07-07 10:22 UTC, alpe approved these changes

2022-07-07 12:34 UTC, merged